version: 0.2

# 
phases:
  install:
    commands:
      - cd source/
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy
  post_build:
    commands:
      - serverless remove